import localFont from "next/font/local";
import "./globals.css";

const banglaFont = localFont({
  src: "../../public/Li Ador Noirrit Regular.ttf",
  variable: "--font-bangla",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${banglaFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
